name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag action-phpcs-code-review:$(date +%s)

    # Additional steps for publishing the Docker image
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag Docker image with version
      run: docker tag action-phpcs-code-review:$(date +%s) ghcr.io/${{ github.repository_owner }}/action-phpcs-code-review:latest

    - name: Publish Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/action-phpcs-code-review:latest
